name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -ldflags "-X main.version=$(git rev-parse --short HEAD)" -v -o . ./...

    - name: Build the Docker image
      run: docker build . -t rmself/gohangout:${GITHUB_REF_NAME}

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push rmself/gohangout:${GITHUB_REF_NAME}
