# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v -o . ./...

    - name: Cache
      uses: actions/cache@v3.0.11
      with:
        path: gohangout
        key: gohangout-${GITHUB_SHA}

  docker:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v3.0.11
      with:
        path: gohangout
        key: gohangout-${GITHUB_SHA}
    - name: Build the Docker image
      run: docker build . --target gohangout -t hub.docker.com/rmself/gohangout:${GITHUB_SHA}
