name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v -o . ./...

    - name: Build the Docker image
      run: docker build . -t rmself/gohangout:${GITHUB_SHA}

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push rmself/gohangout:${GITHUB_SHA}
